routes/web.php
<?php

Route::get('/', function () {
    return redirect('/pt');
});

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['namespace' => 'Admin', 'prefix' => 'cms', 'as' => 'admin.'], function () {
    Route::get('/', 'Auth\HomeController@index')->name('home');
    Route::get('home', 'Auth\HomeController@index')->name('home');

    //Admin Login
    Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('login', 'Auth\LoginController@login');
    Route::post('logout', 'Auth\LoginController@logout')->name('logout');

    //Admin Register
    Route::get('register', 'Auth\RegisterController@showRegistrationForm');
    Route::post('register', 'Auth\RegisterController@register');

    //Admin Passwords
    Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
    Route::post('password/reset', 'Auth\ResetPasswordController@reset');
    Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm');
    Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm');

    // Cadastros
    Route::group(['middleware' => 'auth:admin'], function () {
        Route::get('image_editor/upload', 'ImageUploadController@index');
        Route::post('image_editor/upload', 'ImageUploadController@imageUpload');

        Route::group(['namespace' => 'Company', 'prefix' => 'empresa', 'as' => 'empresa.'], function () {
            Route::get('institucional', 'InstitutionalController@index')->name('institucional');
            Route::post('institucional/store', 'InstitutionalController@store')->name('institucional.store');
            Route::post('institucional/store/{id}', 'InstitutionalController@store')->name('institucional.store.{id}');

            // Rotas Galeria Institucional
            Route::post('institucional/galeria/store/', 'InstitutionalController@storeGallery')->name('institucional.galeria.store');
            Route::post('institucional/galeria/reorder', 'InstitutionalController@sortableGallery')->name('institucional.galeria.reorder');
            Route::get('institucional/galeria/delete/{id}', 'InstitutionalController@destroyItemGallery')->name('institucional.galeria.delete.{id}');
            Route::get('institucional/get_items_gallery', 'InstitutionalController@getItemsGallery')->name('institucional.get_items_gallery');

            // Rotas de Conceitos Estrategicos Institucionais
            Route::post('institucional/conceitos/reorder', 'InstitutionalController@sortableConcept')->name('institucional.conceitos.reorder');
            Route::post('institucional/conceitos/store', 'InstitutionalController@storeConcept')->name('institucional.conceitos.store');
            Route::post('institucional/conceitos/update/{id}', 'InstitutionalController@updateConcept')->name('institucional.conceitos.update.{id}');
            Route::get('institucional/conceitos/editar/{id}', 'InstitutionalController@editConcept')->name('institucional.conceitos.editar.{id}');
            Route::get('institucional/conceitos/delete/{id}', 'InstitutionalController@destroyConcept')->name('institucional.conceitos.delete.{id}');

            // Rotas de Certificações
            Route::get('certificacoes', 'CertificationController@index')->name('certificacoes');
            Route::post('certificacoes/reorder', 'CertificationController@sortable')->name('certificacoes.reorder');
            Route::post('certificacoes/store', 'CertificationController@store')->name('certificacoes.store');
            Route::post('certificacoes/update/{id}', 'CertificationController@update')->name('certificacoes.update.{id}');
            Route::get('certificacoes/editar/{id}', 'CertificationController@edit')->name('certificacoes.editar.{id}');
            Route::get('certificacoes/delete/{id}', 'CertificationController@destroy')->name('certificacoes.delete.{id}');

            // Rotas de Responsabilidades Sociais
            Route::get('responsabilidade_social', 'SocialResponsabilityController@index')->name('responsabilidade_social');
            Route::post('responsabilidade_social/store', 'SocialResponsabilityController@store')->name('responsabilidade_social.store');
            Route::post('responsabilidade_social/store/{id}', 'SocialResponsabilityController@store')->name('responsabilidade_social.store.{id}');

            // Rotas de Responsabilidades Sociais Projetos
            Route::post('responsabilidade_social/projetos/reorder', 'SocialResponsabilityController@sortableProjects')->name('responsabilidade_social.projetos.reorder');
            Route::post('responsabilidade_social/projetos/store', 'SocialResponsabilityController@storeProjects')->name('responsabilidade_social.projetos.store');
            Route::post('responsabilidade_social/projetos/update/{id}', 'SocialResponsabilityController@updateProjects')->name('responsabilidade_social.projetos.update.{id}');
            Route::get('responsabilidade_social/projetos/editar/{id}', 'SocialResponsabilityController@editProjects')->name('responsabilidade_social.projetos.editar.{id}');
            Route::get('responsabilidade_social/projetos/delete/{id}', 'SocialResponsabilityController@destroyProjects')->name('responsabilidade_social.projetos.delete.{id}');

            // Rotas de Parceiros
            Route::get('parcerias', 'PartnersController@index')->name('parcerias');
            Route::post('parcerias/store', 'PartnersController@store')->name('parcerias.store');
            Route::post('parcerias/store/{id}', 'PartnersController@store')->name('parcerias.store.{id}');

            // Rotas de GALERIA PARCEIROS
            Route::post('parcerias/galeria/reorder', 'PartnersController@sortableGallery')->name('parcerias.galeria.reorder');
            Route::post('parcerias/galeria/store', 'PartnersController@storeGallery')->name('parcerias.galeria.store');
            Route::post('parcerias/galeria/update/{id}', 'PartnersController@updateGallery')->name('parcerias.galeria.update.{id}');
            Route::get('parcerias/galeria/editar/{id}', 'PartnersController@editGallery')->name('parcerias.galeria.editar.{id}');
            Route::get('parcerias/galeria/delete/{id}', 'PartnersController@destroyGallery')->name('parcerias.galeria.delete.{id}');

            // Rotas de DEPOIMENTOS PARCEIROS
            Route::post('parcerias/depoimentos/reorder', 'PartnersController@sortableTestimonials')->name('parcerias.depoimentos.reorder');
            Route::post('parcerias/depoimentos/store', 'PartnersController@storeTestimonials')->name('parcerias.depoimentos.store');
            Route::post('parcerias/depoimentos/update/{id}', 'PartnersController@updateTestimonials')->name('parcerias.depoimentos.update.{id}');
            Route::get('parcerias/depoimentos/editar/{id}', 'PartnersController@editTestimonials')->name('parcerias.depoimentos.editar.{id}');
            Route::get('parcerias/depoimentos/delete/{id}', 'PartnersController@destroyTestimonials')->name('parcerias.depoimentos.delete.{id}');

            Route::get('produtos_sob_medida', 'CustomProductsController@index')->name('produtos_sob_medida');
            Route::post('produtos_sob_medida/store', 'CustomProductsController@store')->name('produtos_sob_medida.store');
            Route::post('produtos_sob_medida/store/{id}', 'CustomProductsController@store')->name('produtos_sob_medida.store.{id}');

            // Rotas Galeria Institucional
            Route::post('produtos_sob_medida/galeria/store/', 'CustomProductsController@storeGallery')->name('produtos_sob_medida.galeria.store');
            Route::post('produtos_sob_medida/galeria/reorder', 'CustomProductsController@sortableGallery')->name('produtos_sob_medida.galeria.reorder');
            Route::get('produtos_sob_medida/galeria/delete/{id}', 'CustomProductsController@destroyItemGallery')->name('produtos_sob_medida.galeria.delete.{id}');
            Route::get('produtos_sob_medida/get_items_gallery', 'CustomProductsController@getItemsGallery')->name('produtos_sob_medida.get_items_gallery');

            // Rotas de Comentários
            Route::get('posts/{post_id}/comentarios/', 'CommentsController@index')->name('posts.{post_id}.comentarios');
            Route::get('posts/{post_id}/comentarios/editar/{id}', 'CommentsController@edit')->name('posts.{post_id}.comentarios.editar.{id}');
            Route::get('posts/{post_id}/comentarios/delete/{id}', 'CommentsController@destroy')->name('posts.{post_id}.comentarios.delete.{id}');
            Route::post('posts/{post_id}/comentarios/update/{id}', 'CommentsController@update')->name('posts.{post_id}.comentarios.update.{id}');
        });

        // Rotas de Sliders
        Route::get('sliders', 'SlidersController@index')->name('sliders');
        Route::post('sliders/reorder', 'SlidersController@sortable')->name('sliders.reorder');
        Route::post('sliders/store', 'SlidersController@store')->name('sliders.store');
        Route::post('sliders/update/{id}', 'SlidersController@update')->name('sliders.update.{id}');
        Route::get('sliders/editar/{id}', 'SlidersController@edit')->name('sliders.editar.{id}');
        Route::get('sliders/delete/{id}', 'SlidersController@destroy')->name('sliders.delete.{id}');

        // Rotas de Catalog
        Route::get('catalogos', 'CatalogController@index')->name('catalogos');
        Route::post('catalogos/reorder', 'CatalogController@sortable')->name('catalogos.reorder');
        Route::post('catalogos/store', 'CatalogController@store')->name('catalogos.store');
        Route::post('catalogos/update/{id}', 'CatalogController@update')->name('catalogos.update.{id}');

resources/views/admin/layouts/partials/contentheader.blade.php
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        @yield('contentheader_title', 'Página inicial')
        <small>@yield('contentheader_description')</small>
    </h1>
    @yield('breadcrumbs')
</section>

resources/views/admin/layouts/partials/controlsidebar.blade.php
<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
    <!-- Create the tabs -->
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
        <li class="active"><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
        <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
        <!-- Home tab content -->
        <div class="tab-pane active" id="control-sidebar-home-tab">
            <h3 class="control-sidebar-heading">{{ trans('adminlte_lang::message.recentactivity') }}</h3>
            <ul class='control-sidebar-menu'>
                <li>
                    <a href='javascript::;'>
                        <i class="menu-icon fa fa-birthday-cake bg-red"></i>
                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">{{ trans('adminlte_lang::message.birthday') }}</h4>
                            <p>{{ trans('adminlte_lang::message.birthdaydate') }}</p>
                        </div>
                    </a>
                </li>
            </ul><!-- /.control-sidebar-menu -->

            <h3 class="control-sidebar-heading">{{ trans('adminlte_lang::message.progress') }}</h3>
            <ul class='control-sidebar-menu'>
                <li>
                    <a href='javascript::;'>
                        <h4 class="control-sidebar-subheading">
                            {{ trans('adminlte_lang::message.customtemplate') }}
                            <span class="label label-danger pull-right">70%</span>
                        </h4>
                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
                        </div>
                    </a>
                </li>
            </ul><!-- /.control-sidebar-menu -->

        </div><!-- /.tab-pane -->
        <!-- Stats tab content -->
        <div class="tab-pane" id="control-sidebar-stats-tab">{{ trans('adminlte_lang::message.statstab') }}</div><!-- /.tab-pane -->
        <!-- Settings tab content -->
        <div class="tab-pane" id="control-sidebar-settings-tab">
            <form method="post">
                <h3 class="control-sidebar-heading">{{ trans('adminlte_lang::message.generalset') }}</h3>
                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        {{ trans('adminlte_lang::message.reportpanel') }}
                        <input type="checkbox" class="pull-right" {{ trans('adminlte_lang::message.checked') }} />
                    </label>
                    <p>
                        {{ trans('adminlte_lang::message.informationsettings') }}
                    </p>
                </div><!-- /.form-group -->
            </form>
        </div><!-- /.tab-pane -->
    </div>
</aside><!-- /.control-sidebar

<!-- Add the sidebar's background. This div must be placed
       immediately after the control sidebar -->
<div class='control-sidebar-bg'></div>

resources/views/admin/layouts/partials/footer.blade.php
<!-- Main Footer -->
<footer class="main-footer">
    <!-- Default to the left -->
    <strong>Copyright &copy; 2017. Adere</strong>
</footer>

resources/views/admin/layouts/partials/mainheader.blade.php
<!-- Main Header -->
<header class="main-header">

    <!-- Logo -->
    <a href="{{ url('admin/home') }}" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>A</b>AD</span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><b>Admin</b> Adere </span>
    </a>

    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top" role="navigation">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">{{ trans('adminlte_lang::message.togglenav') }}</span>
        </a>
        <!-- Navbar Right Menu -->
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <!-- Messages: style can be found in dropdown.less-->
                @if (Auth::guest())
                    <li><a href="{{ url('admin/register') }}">{{ trans('adminlte_lang::message.register') }}</a></li>
                    <li><a href="{{ url('admin/login') }}">{{ trans('adminlte_lang::message.login') }}</a></li>
                @else
                    @if(count($sharedData->get('items_post_comments')) > 0)
                        <li class="dropdown messages-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-bell-o"></i>
                                <span class="label label-danger">{{count($sharedData->get('items_post_comments')) + count($sharedData->get('items_comment_answers'))}}</span>
                            </a>
                            <ul class="dropdown-menu">
                                <li class="header">{{count($sharedData->get('items_post_comments'))}} comentários e {{count($sharedData->get('items_comment_answers'))}} respostas aguardando aprovação</li>
                                <li>
                                    <!-- inner menu: contains the actual data -->
                                    <ul class="menu ">
                                        @foreach($sharedData->get('items_post_comments') as $comment)
                                            <li class="list-comment"><!-- start message -->
                                                <a href="{{ url('/cms/blog/posts/'.$comment->post->id.'/comentarios/editar/'.$comment->id) }}">
                                                    <h4>
                                                        {{$comment->title}}
                                                        <small><i class="fa fa-clock-o"></i> {{ (\Carbon\Carbon::now()->diffInDays($comment->created_at)) > 0 ? \Carbon\Carbon::now()->diffInDays($comment->created_at).' dias atrás' : 'hoje' }}</small>
                                                    </h4>
                                                    <p>{{$comment->text}}</p>
                                                </a>
                                            </li>
                                        @endforeach
                                        @foreach($sharedData->get('items_comment_answers') as $comment_answer)
                                            <li class="list-answer"><!-- start message -->
                                                <a href="{{ url('/cms/blog/posts/'.$comment_answer->comment->post->id.'/comentarios/'.$comment_answer->post_comments_id.'/respostas/editar/'.$comment_answer->id) }}">
                                                    <h4>
                                                        <i class="fa fa-commenting"></i> {{$comment_answer->title}}
                                                        <small><i class="fa fa-clock-o"></i> {{ (\Carbon\Carbon::now()->diffInDays($comment_answer->created_at)) > 0 ? \Carbon\Carbon::now()->diffInDays($comment_answer->created_at).' dias atrás' : 'hoje' }}</small>
                                                    </h4>
                                                    <p>{{$comment_answer->text}}</p>
                                                </a>
                                            </li>
                                        @endforeach
                                    </ul>
                                </li>
                            </ul>
                        </li>
                    @endif
                <!-- User Account Menu -->
                    <li class="dropdown user user-menu">
                        <!-- Menu Toggle Button -->
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <!-- The user image in the navbar-->
                            <img src="{{ Gravatar::get($user->email) }}" class="user-image" alt="User Image"/>
                            <!-- hidden-xs hides the username on small devices so only the image appears. -->
                            <span class="hidden-xs">{{ Auth::user()->name }}</span>
                        </a>
                        <ul class="dropdown-menu">
                            <!-- The user image in the menu -->
                            <li class="user-header">
                                <img src="{{ Gravatar::get($user->email) }}" class="img-circle" alt="User Image"/>
                                <p>
                                    {{ Auth::user()->name }}
                                    <small>Logado</small>
                                </p>
                            </li>
                            <!-- Menu Footer-->
                            <li class="user-footer">
                                <div class="pull-right">
                                    <a href="{{ route('admin.logout') }}" class="btn btn-default btn-flat"
                                       onclick="event.preventDefault();
                                                 document.getElementById('logout-form').submit();">
                                        Sair
                                    </a>

                                    <form id="logout-form" action="{{ route('admin.logout') }}" method="POST"
                                          style="display: none;">
                                        {{ csrf_field() }}
                                        <input type="submit" value="logout" style="display: none;">
                                    </form>

                                </div>
                            </li>
                        </ul>
                    </li>
            @endif

            <!-- Control Sidebar Toggle Button -->
            </ul>
        </div>
    </nav>
</header>

resources/views/admin/layouts/partials/scripts.blade.php
<!-- REQUIRED JS SCRIPTS -->

<!-- JQuery and bootstrap are required by Laravel 5.3 in resources/assets/js/bootstrap.js-->
<!-- Laravel App -->
<script src="{{ asset('admin/js/app.js') }}" type="text/javascript"></script>

<!-- Optionally, you can add Slimscroll and FastClick plugins.
      Both of these plugins are recommended to enhance the
      user experience. Slimscroll is required when using the
      fixed layout. -->
<script>
    window.Laravel = {!! json_encode([
        'csrfToken' => csrf_token(),
    ]) !!};
</script>

resources/views/admin/layouts/partials/scripts_auth.blade.php
<!-- Compiled app javascript -->
<script src="{{ asset('admin/js/app.js') }}"></script>

resources/views/admin/layouts/partials/sidebar.blade.php
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

        <!-- Sidebar user panel (optional) -->
        @if (! Auth::guest())
            <div class="user-panel">
                <div class="pull-left image">
                    <img src="{{ Gravatar::get($user->email) }}" class="img-circle" alt="User Image"/>
                </div>
                <div class="pull-left info">
                    <p>{{ Auth::user()->name }}</p>
                    <!-- Status -->
                    <a href="#"><i class="fa fa-circle text-success"></i> {{ trans('adminlte_lang::message.online') }}
                    </a>
                </div>
            </div>
    @endif

    <!-- Sidebar Menu -->
        <ul class="sidebar-menu">
            <li class="header">{{ trans('adminlte_lang::message.header') }}</li>
            <!-- Optionally, you can add icons to the links -->
            <li {{ Request::segment(2) == "home" ? 'class=active' : '' }}>
                <a href="{{ route('admin.home') }}">
                    <i class='fa fa-home'></i> <span>Página Inicial</span>
                </a>
            </li>
            <li class="treeview {{ Request::segment(2) == "empresa" ? 'active' : '' }}">
                <a href="#">
                    <i class='fa fa-building-o'></i> <span>Empresa</span> <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li {{ Request::segment(3) == "institucional" ? 'class=active' : '' }}><a
                                href="{{ route('admin.empresa.institucional') }}"><i class='fa fa-bank'></i>
                            Institucional</a></li>
                    <li {{ Request::segment(3) == "certificacoes" ? 'class=active' : '' }}><a
                                href="{{ route('admin.empresa.certificacoes') }}"><i class='fa fa-certificate'></i>
                            Certificações</a></li>
                    <li {{ Request::segment(3) == "responsabilidade_social" ? 'class=active' : '' }}><a
                                href="{{ route('admin.empresa.responsabilidade_social') }}"><i
                                    class='fa fa-recycle'></i> Responsabilidades Sociais</a></li>
                    <li {{ Request::segment(3) == "parcerias" ? 'class=active' : '' }}><a
                                href="{{ route('admin.empresa.parcerias') }}"><i class='fa fa-handshake-o'></i>
                            Parcerias</a></li>
                    <li {{ Request::segment(3) == "produtos_sob_medida" ? 'class=active' : '' }}><a
                                href="{{ route('admin.empresa.produtos_sob_medida') }}"><i class='fa fa-sliders'></i>
                            Produtos sob medida</a></li>
                </ul>
            </li>
            <li class="treeview {{ Request::segment(2) == "blog" ? 'active' : '' }}">
                <a href="#">
                    <i class='fa fa-commenting'></i> <span>Blog</span> <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    {{--<li {{ Request::segment(3) == "categorias" ? 'class=active' : '' }}><a
                                href="{{ route('admin.blog.categorias') }}"><i class='fa fa-bookmark'></i>
                            Categorias</a></li>--}}
                    <li {{ Request::segment(3) == "posts" ? 'class=active' : '' }}><a
                                href="{{ route('admin.blog.posts') }}"><i class='fa fa-comments-o'></i>
                            Posts</a></li>
                </ul>
            </li>
            <li class="treeview {{ Request::segment(2) == "produtos" ? 'active' : '' }}">
                <a href="#">
                    <i class='fa fa-shopping-bag'></i> <span>Produtos</span> <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li {{ Request::segment(3) == "categorias" ? 'class=active' : '' }}><a
                                href="{{ route('admin.produtos.categorias') }}"><i class='fa fa-tag'></i>
                            Categorias(TIPO)</a></li>
                    <li {{ Request::segment(3) == "subcategorias" ? 'class=active' : '' }}><a
                                href="{{ route('admin.produtos.subcategorias') }}"><i class='fa fa-tags'></i>
                            Subcategorias(Família)</a></li>
                    <li {{ Request::segment(3) == "lista" ? 'class=active' : '' }}><a
                                href="{{ route('admin.produtos.lista') }}"><i class='fa fa-shopping-bag'></i>
                            Lista de produtos</a></li>
                    <li {{ Request::segment(3) == "arquivos" ? 'class=active' : '' }}><a
                                href="{{ route('admin.produtos.arquivos') }}"><i class='fa fa-archive'></i>
                            Arquivos</a></li>
                    <li {{ Request::segment(3) == "aplicacoes" ? 'class=active' : '' }}><a
                                href="{{ route('admin.produtos.aplicacoes') }}"><i class='fa fa-arrows-h'></i>
                            Aplicações</a></li>
                </ul>
            </li>
            <li class="treeview {{ Request::segment(2) == "mercados" ? 'active' : '' }}">
                <a href="#">
                    <i class='fa fa-briefcase'></i> <span>Mercados</span> <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li {{ Request::segment(3) == "categorias" ? 'class=active' : '' }}><a
                                href="{{ route('admin.mercados.categorias') }}"><i class='fa fa-tag'></i>
                            Categorias</a></li>
                    <li {{ Request::segment(3) == "arquivos" ? 'class=active' : '' }}><a
                                href="{{ route('admin.mercados.arquivos') }}"><i class='fa fa-archive'></i>
                            Arquivos</a></li>
                </ul>
            </li>
            <li class="treeview {{ Request::segment(2) == "marcas" ? 'active' : '' }}">
                <a href="#">
                    <i class='fa fa-flag'></i> <span>Nossas Marcas</span> <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li {{ Request::segment(3) == "categorias" ? 'class=active' : '' }}><a
                                href="{{ route('admin.marcas.lista') }}"><i class='fa fa-tag'></i>
                            Marcas</a></li>
                </ul>
            </li>

            <li class="treeview {{ Request::segment(2) == "catalogos" || Request::segment(2) == "banco_de_imagens" || Request::segment(2) == "faq"  ? 'active' : '' }}">
                <a href="#">
                    <i class='fa fa-flag'></i> <span>Serviços</span> <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li {{ Request::segment(2) == "catalogos" ? 'class=active' : '' }}>
                        <a href="{{ route('admin.catalogos') }}">
                            <i class='fa fa-book'></i> <span>Catálogos</span>
                        </a>
                    </li>
                    <li {{ Request::segment(2) == "banco_de_imagens" ? 'class=active' : '' }}>
                        <a href="{{ route('admin.banco_de_imagens') }}">
                            <i class='fa fa-image'></i> <span>Banco de Imagens</span>
                        </a>
                    </li>
                    <li {{ Request::segment(2) == "faq" ? 'class=active' : '' }}>
                        <a href="{{ route('admin.faq') }}">
                            <i class='fa fa-question-circle-o'></i> <span>Perguntas Frequentes</span>
                        </a>
                    </li>
                </ul>
            </li>
            <li  class="treeview {{ Request::segment(2) == "textos" || Request::segment(2) == "configuracoes"  ? 'active' : '' }}">
                <a href="#">
                    <i class='fa fa-cogs'></i> <span>Dados gerais do site</span> <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li {{ Request::segment(2) == "sliders" ? 'class=active' : '' }}>
                        <a href="{{ route('admin.sliders') }}">
                            <i class='fa fa-picture-o'></i> <span>Slider Página inicial</span>
                        </a>
                    </li>
                    <li {{ Request::segment(2) == "banners" ? 'class=active' : '' }}>
                        <a href="{{ route('admin.banners') }}">
                            <i class='fa fa-picture-o'></i> <span>Banners</span>
                        </a>
                    </li>
                    <li {{ Request::segment(2) == "textos" ? 'class=active' : '' }}>
                        <a href="{{ route('admin.textos') }}">
                            <i class='fa fa-align-justify'></i> <span>Textos</span>
                        </a>
                    </li>
                    <li {{ Request::segment(2) == "configuracoes" ? 'class=active' : '' }}>
                        <a href="{{ route('admin.configuracoes') }}">
                            <i class='fa fa-comments'></i> <span>Midías, contatos e Seo</span>
                        </a>
                    </li>
                    <li {{ Request::segment(2) == "configuracoes" ? 'class=active' : '' }}>
                        <a href="{{ route('admin.newsletter') }}">
                            <i class='fa fa-envelope-o'></i> <span>Newsletter</span>
                        </a>
                    </li>
                    <li {{ Request::segment(2) == "clientes_download_arquivos" ? 'class=active' : '' }}>
                        <a href="{{ route('admin.clientes_download_arquivos') }}">
                            <i class='fa fa-envelope-o'></i> <span>Clientes que fizeram download</span>
                        </a>
                    </li>
                </ul>
            </li>

        </ul><!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
</aside>