routes/web.php
<?php

Route::get('/', function () {
    return redirect('/pt');
});

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['namespace' => 'Admin', 'prefix' => 'cms', 'as' => 'admin.'], function () {
    Route::get('/', 'Auth\HomeController@index')->name('home');
    Route::get('home', 'Auth\HomeController@index')->name('home');

    //Admin Login
    Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('login', 'Auth\LoginController@login');
    Route::post('logout', 'Auth\LoginController@logout')->name('logout');

    //Admin Register
    Route::get('register', 'Auth\RegisterController@showRegistrationForm');
    Route::post('register', 'Auth\RegisterController@register');

    //Admin Passwords
    Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
    Route::post('password/reset', 'Auth\ResetPasswordController@reset');
    Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm');
    Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm');

    // Cadastros
    Route::group(['middleware' => 'auth:admin'], function () {
        Route::get('image_editor/upload', 'ImageUploadController@index');
        Route::post('image_editor/upload', 'ImageUploadController@imageUpload');

        Route::group(['namespace' => 'Company', 'prefix' => 'empresa', 'as' => 'empresa.'], function () {
            Route::get('institucional', 'InstitutionalController@index')->name('institucional');
            Route::post('institucional/store', 'InstitutionalController@store')->name('institucional.store');
            Route::post('institucional/store/{id}', 'InstitutionalController@store')->name('institucional.store.{id}');

            // Rotas Galeria Institucional
            Route::post('institucional/galeria/store/', 'InstitutionalController@storeGallery')->name('institucional.galeria.store');
            Route::post('institucional/galeria/reorder', 'InstitutionalController@sortableGallery')->name('institucional.galeria.reorder');
            Route::get('institucional/galeria/delete/{id}', 'InstitutionalController@destroyItemGallery')->name('institucional.galeria.delete.{id}');
            Route::get('institucional/get_items_gallery', 'InstitutionalController@getItemsGallery')->name('institucional.get_items_gallery');

            // Rotas de Conceitos Estrategicos Institucionais
            Route::post('institucional/conceitos/reorder', 'InstitutionalController@sortableConcept')->name('institucional.conceitos.reorder');
            Route::post('institucional/conceitos/store', 'InstitutionalController@storeConcept')->name('institucional.conceitos.store');
            Route::post('institucional/conceitos/update/{id}', 'InstitutionalController@updateConcept')->name('institucional.conceitos.update.{id}');
            Route::get('institucional/conceitos/editar/{id}', 'InstitutionalController@editConcept')->name('institucional.conceitos.editar.{id}');
            Route::get('institucional/conceitos/delete/{id}', 'InstitutionalController@destroyConcept')->name('institucional.conceitos.delete.{id}');

            // Rotas de Certificações
            Route::get('certificacoes', 'CertificationController@index')->name('certificacoes');
            Route::post('certificacoes/reorder', 'CertificationController@sortable')->name('certificacoes.reorder');
            Route::post('certificacoes/store', 'CertificationController@store')->name('certificacoes.store');
            Route::post('certificacoes/update/{id}', 'CertificationController@update')->name('certificacoes.update.{id}');
            Route::get('certificacoes/editar/{id}', 'CertificationController@edit')->name('certificacoes.editar.{id}');
            Route::get('certificacoes/delete/{id}', 'CertificationController@destroy')->name('certificacoes.delete.{id}');

            // Rotas de Responsabilidades Sociais
            Route::get('responsabilidade_social', 'SocialResponsabilityController@index')->name('responsabilidade_social');
            Route::post('responsabilidade_social/store', 'SocialResponsabilityController@store')->name('responsabilidade_social.store');
            Route::post('responsabilidade_social/store/{id}', 'SocialResponsabilityController@store')->name('responsabilidade_social.store.{id}');

            // Rotas de Responsabilidades Sociais Projetos
            Route::post('responsabilidade_social/projetos/reorder', 'SocialResponsabilityController@sortableProjects')->name('responsabilidade_social.projetos.reorder');
            Route::post('responsabilidade_social/projetos/store', 'SocialResponsabilityController@storeProjects')->name('responsabilidade_social.projetos.store');
            Route::post('responsabilidade_social/projetos/update/{id}', 'SocialResponsabilityController@updateProjects')->name('responsabilidade_social.projetos.update.{id}');
            Route::get('responsabilidade_social/projetos/editar/{id}', 'SocialResponsabilityController@editProjects')->name('responsabilidade_social.projetos.editar.{id}');
            Route::get('responsabilidade_social/projetos/delete/{id}', 'SocialResponsabilityController@destroyProjects')->name('responsabilidade_social.projetos.delete.{id}');

            // Rotas de Parceiros
            Route::get('parcerias', 'PartnersController@index')->name('parcerias');
            Route::post('parcerias/store', 'PartnersController@store')->name('parcerias.store');
            Route::post('parcerias/store/{id}', 'PartnersController@store')->name('parcerias.store.{id}');

            // Rotas de GALERIA PARCEIROS
            Route::post('parcerias/galeria/reorder', 'PartnersController@sortableGallery')->name('parcerias.galeria.reorder');
            Route::post('parcerias/galeria/store', 'PartnersController@storeGallery')->name('parcerias.galeria.store');
            Route::post('parcerias/galeria/update/{id}', 'PartnersController@updateGallery')->name('parcerias.galeria.update.{id}');
            Route::get('parcerias/galeria/editar/{id}', 'PartnersController@editGallery')->name('parcerias.galeria.editar.{id}');
            Route::get('parcerias/galeria/delete/{id}', 'PartnersController@destroyGallery')->name('parcerias.galeria.delete.{id}');

            // Rotas de DEPOIMENTOS PARCEIROS
            Route::post('parcerias/depoimentos/reorder', 'PartnersController@sortableTestimonials')->name('parcerias.depoimentos.reorder');
            Route::post('parcerias/depoimentos/store', 'PartnersController@storeTestimonials')->name('parcerias.depoimentos.store');
            Route::post('parcerias/depoimentos/update/{id}', 'PartnersController@updateTestimonials')->name('parcerias.depoimentos.update.{id}');
            Route::get('parcerias/depoimentos/editar/{id}', 'PartnersController@editTestimonials')->name('parcerias.depoimentos.editar.{id}');
            Route::get('parcerias/depoimentos/delete/{id}', 'PartnersController@destroyTestimonials')->name('parcerias.depoimentos.delete.{id}');

            Route::get('produtos_sob_medida', 'CustomProductsController@index')->name('produtos_sob_medida');
            Route::post('produtos_sob_medida/store', 'CustomProductsController@store')->name('produtos_sob_medida.store');
            Route::post('produtos_sob_medida/store/{id}', 'CustomProductsController@store')->name('produtos_sob_medida.store.{id}');

            // Rotas Galeria Institucional
            Route::post('produtos_sob_medida/galeria/store/', 'CustomProductsController@storeGallery')->name('produtos_sob_medida.galeria.store');
            Route::post('produtos_sob_medida/galeria/reorder', 'CustomProductsController@sortableGallery')->name('produtos_sob_medida.galeria.reorder');
            Route::get('produtos_sob_medida/galeria/delete/{id}', 'CustomProductsController@destroyItemGallery')->name('produtos_sob_medida.galeria.delete.{id}');
            Route::get('produtos_sob_medida/get_items_gallery', 'CustomProductsController@getItemsGallery')->name('produtos_sob_medida.get_items_gallery');

            // Rotas de Comentários
            Route::get('posts/{post_id}/comentarios/', 'CommentsController@index')->name('posts.{post_id}.comentarios');
            Route::get('posts/{post_id}/comentarios/editar/{id}', 'CommentsController@edit')->name('posts.{post_id}.comentarios.editar.{id}');
            Route::get('posts/{post_id}/comentarios/delete/{id}', 'CommentsController@destroy')->name('posts.{post_id}.comentarios.delete.{id}');
            Route::post('posts/{post_id}/comentarios/update/{id}', 'CommentsController@update')->name('posts.{post_id}.comentarios.update.{id}');
        });

        // Rotas de Sliders
        Route::get('sliders', 'SlidersController@index')->name('sliders');
        Route::post('sliders/reorder', 'SlidersController@sortable')->name('sliders.reorder');
        Route::post('sliders/store', 'SlidersController@store')->name('sliders.store');
        Route::post('sliders/update/{id}', 'SlidersController@update')->name('sliders.update.{id}');
        Route::get('sliders/editar/{id}', 'SlidersController@edit')->name('sliders.editar.{id}');
        Route::get('sliders/delete/{id}', 'SlidersController@destroy')->name('sliders.delete.{id}');

        // Rotas de Catalog
        Route::get('catalogos', 'CatalogController@index')->name('catalogos');
        Route::post('catalogos/reorder', 'CatalogController@sortable')->name('catalogos.reorder');
        Route::post('catalogos/store', 'CatalogController@store')->name('catalogos.store');
        Route::post('catalogos/update/{id}', 'CatalogController@update')->name('catalogos.update.{id}');

app/Http/Controllers/Admin/Company/CertificationController.php
<?php

namespace App\Http\Controllers\Admin\Company;

use App\Entities\Company\Certification\Certification;
use App\Http\Controllers\Controller;
use App\Services\StandardService;
use Illuminate\Http\Request;

use App\Http\Requests;

use File;
use JavaScript;
use Response;
use Redirect;
use Session;

class CertificationController extends Controller
{

    /**
     * @var Certification
     */
    protected $repository;

    /**
     * @var StandardService
     */
    protected $standard;

    public function __construct(Certification $repository, StandardService $standard)
    {
        $this->repository = $repository;
        $this->standard = $standard;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $items_list = $this->repository->orderBy('order','desc')->get();

        $items_list->map(function ($item_list) {
            if(!empty($item_list->getTranslation('pt')->title)) $item_list->title_pt = $item_list->getTranslation('pt')->title;
            else $item_list->title_pt = 'sem título';
        });

        JavaScript::put([
            'items_list_data' => $items_list
        ]);

        return view('admin.company.certification.index');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request $request
     *
     * @return \Illuminate\Http\Response
     */
    // SALVANDO
    public function store(Request $request)
    {
        try {
            $item = new $this->repository;

            foreach (['pt', 'en', 'es'] as $locale) {
                $item->translateOrNew($locale)->title = $request->input('title_'.$locale);
                $item->translateOrNew($locale)->text = $request->input('text_'.$locale);
            }

            $image = $this->standard->doUpload($request->file('file_image'),'_files/certificacoes/',228,false);
            $item->image = $image;

            $pdf_name = $this->standard->anyFile($request->file('file_pdf'),'_files/certificacoes/',$request->file('file_pdf')->getClientOriginalName());
            $item->pdf = $pdf_name;

            $ultimo_item = $this->repository->orderBy('order','desc')->first();
            $item->order = !empty($ultimo_item) ? $ultimo_item->order+1 : 1;

            $item->save();

            Session::flash('success', 'Certificado criado com sucesso!');
        } catch (ValidatorException $e) {

            return redirect()->back()->withErrors($e->getMessageBag())->withInput();
        }
        return Redirect::to('/cms/empresa/certificacoes');
    }

    /**
     * @param Request $request
     * @param int $id
     * @return mixed
     */
    public function update(Request $request, $id=0)
    {
        try {
            $item = $this->repository->find($id);

            foreach (['pt', 'en', 'es'] as $locale) {
                $item->translateOrNew($locale)->title = $request->input('title_'.$locale);
                $item->translateOrNew($locale)->text = $request->input('text_'.$locale);
            }

            if (!empty($request->file('file_image'))) {
                File::delete('_files/certificacoes/' . $item->image);
                $image_name = $this->standard->doUpload($request->file('file_image'),'_files/certificacoes/',228,false);
                $item->image = $image_name;
            }

            if (!empty($request->file('file_pdf'))) {
                File::delete('_files/certificacoes/' . $item->pdf);
                $pdf_name = $this->standard->anyFile($request->file('file_pdf'),'_files/certificacoes/',$request->file('file_pdf')->getClientOriginalName());
                $item->pdf = $pdf_name;
            }

            $item->save();

            Session::flash('success', 'Certificado atualizado com sucesso!');
        } catch (ValidatorException $e) {

            return redirect()->back()->withErrors($e->getMessageBag())->withInput();
        }
        return Redirect::to('/cms/empresa/certificacoes');
    }

    /**
     * @param Request $request
     * @return int
     */
    public function sortable(Request $request)
    {
        $this->standard->doReorder($request->input('items'), true, $this->repository);
        return 2;
    }

    /**
     * @param $id
     * @return int
     */
    public function destroy($id)
    {
        $item = $this->repository->find($id);

        if(!empty($item->image)) File::delete('_files/certificacoes/'.$item->image);

        if(!empty($item->pdf)) File::delete('_files/certificacoes/'.$item->pdf);

        $item->delete();

        Session::flash('success', 'Item excluído com sucesso!');
        return Redirect::to('/cms/empresa/certificacoes');
    }

    /**
     * @param int $id
     * @return mixed
     */
    public function edit($id=0)
    {
        $item = $this->repository->find($id);
        return view('admin.company.certification.edit', compact('item'));
    }
}

resources/views/admin/company/certification/edit.blade.php
@extends('admin.layouts.app')

@section('htmlheader_title','Certificações')
@section('contentheader_title','Certificações')
@section('breadcrumbs')
	<ol class="breadcrumb">
		<li><i class="fa fa-building-o"></i> Empresa</li>
		<li class="active"><a href="{{ route('admin.empresa.certificacoes') }}">Certificações</a></li>
	</ol>
@endsection

@section('main-content')
	<div class="row">
		<div class="col-xs-12">
			<div class="box box-info">
				<div class="box-header">
					<h3 class="box-title">Editar Campos</h3>
				</div>
				<form action="{{ route('admin.empresa.certificacoes.update.{id}', array($item->id)) }}" method="POST" enctype="multipart/form-data">
					{!! csrf_field() !!}
					<div class="box-body">
						<div class="col-xs-4">
							<div class="form-group">
								<label for="image">Imagem Ícone:</label>
								<div class="upload">
									<div class="btn btn-primary">Atualizar Imagem</div>
									<input type="file" id="image" name="file_image" />
									@if (!empty($item->id))
										(<a href="{{ asset('_files/certificacoes/' . $item->image) }}" title="ver imagem atual" target="_blank">Ver Imagem Atual</a>)
									@endif
								</div>
							</div>
						</div>
						<div class="col-xs-4">
							<div class="form-group">
								<label for="pdf">Arquivo PDF:</label>
								<div class="upload">
									<div class="btn btn-primary">Atualizar PDF</div>
									<input type="file" id="pdf" name="file_pdf" />
									@if (!empty($item->id))
										(<a href="{{ asset('_files/certificacoes/' . $item->pdf) }}" title="ver imagem atual" target="_blank">Ver Imagem Atual</a>)
									@endif
								</div>
							</div>
						</div>
						<div class="clearfix"></div>
						@foreach(['pt','en','es'] as $locale)
							<div class="col-md-4">
								<!-- DIRECT CHAT SUCCESS -->
								<div class="box {{($locale == 'pt' ? 'box-success' : ($locale == 'en' ? 'box-danger' : ($locale == 'es' ? 'box-warning' : ''))) }} direct-chat direct-chat-success">
									<div class="box-header with-border">
										<h3 class="box-title"><span class="icon-language icon-{{$locale}}"></span> {{($locale == 'pt' ? 'Português' : ($locale == 'en' ? 'Inglês' : ($locale == 'es' ? 'Espanhol' : ''))) }}</h3>
										<div class="box-tools pull-right">
											<button type="button" class="btn btn-box-tool" data-widget="collapse">
												<i class="fa fa-minus"></i>
											</button>
										</div>
									</div>
									<!-- /.box-header -->
									<div class="box-body">
										<div class="col-xs-12">
											<div class="form-group">
												<label>Título:</label>
												<input type="text" name="title_{{$locale}}" class="form-control" value="{{ empty($item->getTranslation($locale)->title) ? old('title') : $item->getTranslation($locale)->title}}">
											</div>
										</div>
										<div class="col-xs-12">
											<div class="form-group">
												<label>Descrição:</label>
												<textarea name="text_{{$locale}}" class="form-control tinymce">{{ empty($item->getTranslation($locale)->title) ? old('text') : $item->getTranslation($locale)->text}}</textarea>
											</div>
										</div>
									</div>
								</div>
								<!--/.direct-chat -->
							</div>
							<!-- /.col -->
						@endforeach
					</div>
					<div class="box-footer">
						<button class="btn btn-primary btn-send pull-right">Salvar</button>
					</div>
				</form>
			</div>
		</div>
	</div>
@endsection

resources/views/admin/company/certification/index.blade.php
@extends('admin.layouts.app')

@section('htmlheader_title','Certificações')
@section('contentheader_title','Certificações')
@section('breadcrumbs')
	<ol class="breadcrumb">
		<li><a href="#"><i class="fa fa-building-o"></i> Empresa</a></li>
		<li class="active">Certificações</li>
	</ol>
@endsection

@section('main-content')
	<div class="row">
		<div class="col-xs-12 col-md-8">
			<div class="box">
				<!-- /.box-header -->
				<div class="box-body table-responsive no-padding">

					<div class="alert alert-success alert-dismissible" v-show="msgSuccessReorder" v-cloak>
						<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
						<h4><i class="icon fa fa-check"></i> @{{ msgSuccess }}</h4>
					</div>

					<vue-table-list :items-list="items_list" urls='{"reorder": "/cms/empresa/certificacoes/reorder","image":"/_files/certificacoes/","delete":"/cms/empresa/certificacoes/delete/","edit":"/cms/empresa/certificacoes/editar/"}'></vue-table-list>
				</div>
				<!-- /.box-body -->
			</div>
			<!-- /.box -->
		</div>
		<div class="col-xs-12 col-md-4">
			<div class="box box-info">
				<div class="box-header">
					<h3 class="box-title">Adicionar Certificado</h3>
				</div>
				<form action="{{ route('admin.empresa.certificacoes.store') }}" class="form-table-list" method="POST" enctype="multipart/form-data">
					{!! csrf_field() !!}
					<div class="box-body">
						<div class="row">
							<div class="col-xs-12">
								<div class="form-group">
									<label for="image">Imagem PDF(printScreen):</label>
									<div class="upload">
										<div class="btn btn-primary">Adicionar Imagem</div>
										<input type="file" id="image" name="file_image" />
									</div>
								</div>
							</div>
							<div class="col-xs-12">
								<div class="form-group">
									<label for="pdf">Arquivo PDF (.pdf):</label>
									<div class="upload">
										<div class="btn btn-primary">Adicionar PDF</div>
										<input type="file" id="pdf" name="file_pdf" accept="application/pdf" />
									</div>
								</div>
							</div>
							@foreach(['pt','en','es'] as $key=>$locale)
								<div class="col-md-12">
									<!-- DIRECT CHAT SUCCESS -->
									<div class="box {{($locale == 'pt' ? 'box-success' : ($locale == 'en' ? 'box-danger' : ($locale == 'es' ? 'box-warning' : ''))) }} direct-chat direct-chat-success {{ $key == 0 ? '' : 'collapsed-box'}}">
										<div class="box-header with-border">
											<h3 class="box-title"><span class="icon-language icon-{{$locale}}"></span> {{($locale == 'pt' ? 'Português' : ($locale == 'en' ? 'Inglês' : ($locale == 'es' ? 'Espanhol' : ''))) }}</h3>
											<div class="box-tools pull-right">
												<button type="button" class="btn btn-box-tool" data-widget="collapse">
													<i class="fa {{ $key == 0 ? 'fa-minus' : 'fa-plus'}}"></i>
												</button>
											</div>
										</div>
										<!-- /.box-header -->
										<div class="box-body">
											<div class="col-xs-12">
												<div class="form-group">
													<label>Título:</label>
													<input type="text" name="title_{{$locale}}" class="form-control">
												</div>
											</div>
											<div class="col-xs-12">
												<div class="form-group">
													<label>Descrição:</label>
													<div class="content-editor">
														<div class="btn {{($locale == 'pt' ? 'btn-success' : ($locale == 'en' ? 'btn-danger' : ($locale == 'es' ? 'btn-warning' : ''))) }} open-editor">Adicionar Descrição</div>
														<div class="modal-editor">
															<div class="overlay-editor"></div>
															<div class="container-editor">
																<div class="close-editor">
																	<span class="fa-stack fa-lg">
																	  <i class="fa fa-circle fa-stack-2x"></i>
																	  <i class="fa fa-close fa-stack-1x fa-inverse"></i>
																	</span>
																</div>
																<textarea class="tinymce" name="text_{{$locale}}" id="text_gallery" cols="30" rows="10"></textarea>
															</div>
														</div>
													</div>
												</div>
											</div>
										</div>
									</div>
									<!--/.direct-chat -->
								</div>
								<!-- /.col -->
							@endforeach
						</div>
						<div class="col-md-12">
							<button class="btn btn-primary btn-send pull-right">Salvar</button>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
@endsection